version: '3.4'

services:
  dev:
    container_name: dev-nodebasic
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: sujan1921/demonode-dev
    ports:
      - 4500:5000
    restart: always

  prod:
    container_name: prod-nodebasic
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: sujan1921/demonode-prod
    ports:
      - 5000:5000
    restart: always
